spring:
  application:
    name: demo01
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useSSL=false&serverTimezone=UTC
    username: root
    password: wtd156211
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatisPlus配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 全局配置
  global-config:
    db-config:
      id-type: auto   #id生成策略为自增
  configuration:
    map-underscore-to-camel-case: true